workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $SCHEDULED_JOB_TO_RUN
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

variables:
  STAGE: TEST
  ENV: TEST
  MAVEN_OPTS: "maven options"
  SONAR_PROJECT_KEY: mobile-test-automation
  CLUSTER_API: CLUSTER_API
  GIT_DEPTH: 5
  NEXUS_HOST: NEXUS_HOST
  SONAR_URL: SONAR_URL
  HTTP_PROXY: HTTP_PROXY
  HTTPS_PROXY: HTTPS_PROXY
  NO_PROXY: localhost,127.0.0.0/8
  MAVEN_CLI_OPTS: "-e -s helpers/mvn-setting.xml --batch-mode"
  SPOT_BUGS_GOAL: "spotbugs:spotbugs"

default:
  artifacts:
    name: "tests-output"
    expire_in: 5 days
    paths:
      - test-output/
    when: always
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - repo
  image: image_name
  tags:
    - E2E
  before_script:
    - echo "$JAVA_HOME"
    - java --version
    - mvn --version

stages:
  - quality
  - test-full
  - test-failed
  - test
  - build
  - package
  - deploy
  - post deploy
  - rollback

quality-gate:
  stage: quality
  script:
    - mvn verify -DskipTests $MAVEN_CLI_OPTS
  artifacts:
    name: "quality-reports"
    expire_in: 5 days
    paths:
      - target/spotbugsXml.xml
      - target/checkstyle-result.xml
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$SCHEDULED_JOB_TO_RUN == "QUALITY"'

API:
  stage: test
  variables:
    KUBERNETES_CPU_REQUEST: KUBERNETES_CPU_REQUEST
    KUBERNETES_CPU_LIMIT: KUBERNETES_CPU_LIMIT
    KUBERNETES_MEMORY_REQUEST: KUBERNETES_MEMORY_REQUEST
    KUBERNETES_MEMORY_LIMIT: KUBERNETES_MEMORY_LIMIT
  tags:
    - TAGS
  script:
    - |
      if [ ${STAGE} = "uat" ]
      then
        export TAGS="(@UAT and (${TAGS})) and not @KnownIssue"
        echo "using TAGS: ${TAGS}"
      else
        export TAGS="(${TAGS}) and not @KnownIssue"
        echo "using TAGS: ${TAGS}"
      fi
    - mvn test -DsuiteXmlFile=path_to_file -Dcucumber.filter.tags="($TAGS)"
  rules:
    - if: '$SCHEDULED_JOB_TO_RUN == "API"'

UI:
  stage: test
  script:
    - mvn test -DsuiteXmlFile=path_to_file
  rules:
    - if: '$SCHEDULED_JOB_TO_RUN == "UI"'
