extent.reporter.spark.start=true
extent.reporter.spark.out=test-output/reports/TestReports.html
extent.reporter.spark.config=src/main/resources/spark-config.xml

screenshot.dir=test-output/screenshots/
screenshot.rel.path=../../test-output/screenshots/

extent.reporter.spark.enable.device=true
extent.reporter.spark.enable.author=true

extent.reporter.spark.prefix.device=@device_
extent.reporter.spark.prefix.author=@author_

#default is true
basefolder.enable.delimiter=true
